# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1097019f656ae912662a4a1326a0a5c179170a3320372b610463dcb3c83687bcb38b1080f8f7a94fa6739d2bb5adfd7f9257ddb84c3b7562845eb7993dc717c4

test:
  secret_key_base: e039b3739ce3ad23930f0daa80a59ce85a8c3eace1f14771f9c4fab1b7e3865166ea5000dd6b0ea81a110e00d5c897f678a5b4684f57877814d690d55ef52dc1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
